# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: workspace/v1/registration.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'workspace/v1/registration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fworkspace/v1/registration.proto\x12\x0cworkspace.v1\"#\n\x12RedeemTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"?\n\x13RedeemTokenResponse\x12\x14\n\x0cworkspace_id\x18\x01 \x01(\t\x12\x12\n\ncreated_by\x18\x02 \x01(\t2i\n\x13RegistrationService\x12R\n\x0bRedeemToken\x12 .workspace.v1.RedeemTokenRequest\x1a!.workspace.v1.RedeemTokenResponseBFZDgithub.com/tiwazs/gnosis-workspace/app/grpc/workspace/v1;workspacev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'workspace.v1.registration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZDgithub.com/tiwazs/gnosis-workspace/app/grpc/workspace/v1;workspacev1'
  _globals['_REDEEMTOKENREQUEST']._serialized_start=49
  _globals['_REDEEMTOKENREQUEST']._serialized_end=84
  _globals['_REDEEMTOKENRESPONSE']._serialized_start=86
  _globals['_REDEEMTOKENRESPONSE']._serialized_end=149
  _globals['_REGISTRATIONSERVICE']._serialized_start=151
  _globals['_REGISTRATIONSERVICE']._serialized_end=256
# @@protoc_insertion_point(module_scope)
