"""Relation table devices and operations

Revision ID: 523b2b01b830
Revises: b8a565757afc
Create Date: 2026-07-05 21:41:52.473629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '523b2b01b830'
down_revision: Union[str, Sequence[str], None] = 'b8a565757afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('operation_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['iot.devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operation_id'], ['iot.operations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='iot'
    )
    op.drop_constraint(op.f('actions_operation_id_fkey'), 'actions', type_='foreignkey')
    op.create_foreign_key(None, 'actions', 'operations', ['operation_id'], ['id'], source_schema='iot', referent_schema='iot', ondelete='CASCADE')
    op.drop_constraint(op.f('coordinates_device_id_fkey'), 'coordinates', type_='foreignkey')
    op.create_foreign_key(None, 'coordinates', 'devices', ['device_id'], ['id'], source_schema='iot', referent_schema='iot', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coordinates', schema='iot', type_='foreignkey')
    op.create_foreign_key(op.f('coordinates_device_id_fkey'), 'coordinates', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'actions', schema='iot', type_='foreignkey')
    op.create_foreign_key(op.f('actions_operation_id_fkey'), 'actions', 'operations', ['operation_id'], ['id'], ondelete='CASCADE')
    op.drop_table('device_operations', schema='iot')
    # ### end Alembic commands ###
